### ISSUE TITLE
Stocks sample app: Scrolling and then dragging the confirmation dialog offsets its position

### ISSUE THREAD

**Issue by marin-bratanov** [telerik/blazor-ui#106] opened 2021-07-08 18:21 UTC
Repro:

1. Click the Delete button on the main page https://demos.telerik.com/blazor-financial-portfolio/
2. scroll the page down
3. try dragging the confirmation window

Actual:
It moves to a wrong position, potentially outside of the viewport.

Expected:
It does not move away from the mouse

Root cause:
The layout of the app produces scrollbars on the parent element of the popup and focusing and moving it causes issues with calculations when those elements are scrolled. In Blazor there is a limit on how far up the DOM you can render popup elements and so you cannot fully take into account all possible CSS and scrolling settings.
You can read more about this here: https://docs.telerik.com/blazor-ui/knowledge-base/common-popup-causes-scroll-on-show and the fix would be similar to one proposed in the linked sample project - ensure that scrollbars are in the content, below the `TelerikRootComponent` and higher level elements have `height:100%` and `overflow:hidden`. In this app, the fix is not that trivial because it has a little more complex layout, responsive layout and a header, however.

Also related and similar in root cause to #104

**Comment by xristianstefanov** [comment] 2022-08-08 14:14
I'm closing this issue here as it is no longer reproduces due to the [above-mentioned item](https://feedback.telerik.com/blazor/1523035-modal-window-moves-away-from-the-cursor-on-drag-start-when-there-is-a-vertical-page-scrollbar-and-the-scroll-position-is-not-top).

**Closed by xristianstefanov** 2022-08-08 14:14 UTC
